### ISSUE TITLE
[Bug] Bench cannot be found in creative menu. Only by Item Search

### ISSUE THREAD

**Issue by RedBeast1959** [SuperMartijn642/Benched#2]
**Version Info**
- Minecraft: 1.19.2
- Forge: 43.1.3
- Benched: benched-1.2.1a-forge-mc1.19.jar

**Description of the Bug**
...
There's no proper creative menu for Benched Mod. In creative mod, I can only find them by item search bar.

**Steps to Reproduce**
...

**Screenshots**
...
![2022-09-04_21 52 53](https://user-images.githubusercontent.com/100399264/188314537-b5bb7fc1-a610-4a87-9380-b5f9bad4d152.png)

**Comment by SuperMartijn642** [comment]
I added them all to the decorations tab now in version 1.2.2.

Thank you for reporting the issue!
