### ISSUE TITLE
Forward application

### ISSUE THREAD

**Issue by Nuttar2004** [SuperMartijn642/Benched#5]
Hello, I am a user from China and I really like your Mod. Can I forward it to the Minecraft website in China?
（https://www.mcmod.cn/）
This website will guide you to the original Modrinth post and will not provide new download paths

**Comment by TaoismDeepLake** [comment]
Nuttar may have some trouble expressing it in English. By "forward", he means to post a link there to your official website and creating a wiki page for you mod, not carrying the jar files directly.
MCMod.cn is a mod wiki in Chinese, he looks forward to introduce your mod to the Chinese community.

**Comment by SuperMartijn642** [comment]
As long as the downloads redirect to CurseForge, I don't mind.
